PALETTE_INDEX_FRAME = 0

;; this is so they can "steal" the dark blue
PALETTE_INDEX_BOMB_COUNT_BG = 0
PALETTE_INDEX_TIMER_BG = 0

PALETTE_INDEX_PLAYFIELD = 12
PALETTE_INDEX_BOMB_COUNT = 3
PALETTE_INDEX_TIMER = 3
PALETTE_INDEX_MINIMAP = 5
PALETTE_INDEX_DIFFICULTY_MENU = 8